---
- name: Add Chrome Apt Key
  apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present

# Setup apt repo
- name: Add Chrome Repo
  apt_repository: repo='deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'

# Install from apt
- name: Install Chrome
  apt: name=google-chrome-stable state=present
